.TH ASN2IDX 1 2007-10-19 NCBI "NCBI Tools User's Manual"
.SH NAME
asn2idx \- index ASN.1 Bioseq-sets for fast access to individual sequences
.SH SYNOPSIS
.B asn2idx
[\|\fB\-\fP\|]
[\|\fB\-b\fP\|]
[\|\fB\-d\fP\ \fIdir\fP\|]
[\|\fB\-f\fP\ \fIfilter\fP\|]
\fB\-p\fP\ \fIpath\fP
[\|\fB\-r\fP\ \fIpath\fP\|]
[\|\fB\-t\fP\|]
[\|\fB\-x\fP\ \fIstr\fP\|]
.SH DESCRIPTION
\fBasn2idx\fP indexes ASN.1 Bioseq-sets (such as GenBank release
files) to speed retrieval of the individual sequences they contain.
For each file that it processes, it yields an output file in the same
directory with the extension \fB.idx\fP.
.SH OPTIONS
A summary of options is included below.
.TP
\fB\-\fP
Print usage message
.TP
\fB\-b\fP
Bioseq-sets are Binary
.TP
\fB\-d\fP\ \fIdir\fP
Required Subdirectory
.TP
\fB\-f\fP\ \fIfilter\fP
Filter (default = \fBgbcon,gbest,gbgss,gbsts\fP)
.TP
\fB\-p\fP\ \fIpath\fP
Path to Files
.TP
\fB\-p\fP\ \fIpath\fP
Path for Results
.TP
\fB\-t\fP
Recurse
.TP
\fB\-x\fP\ \fIstr\fP
File Selection Substring (default = \fB.aso\fP)
.SH AUTHOR
The National Center for Biotechnology Information.
.SH SEE ALSO
.BR asn2asn (1),
.BR asndhuff (1).
