.TH SBTEDIT 1 2005-11-04 NCBI "NCBI Tools User's Manual"
.SH NAME
sbtedit \- GenBank submission template editor
.SH SYNOPSIS
.B sbtedit
.SH DESCRIPTION
\fBPsbtedit\fP is a graphical editor for GenBank submission templates,
which \fBPsequin\fP(1) and \fBPtbl2asn(1)\fP can combine with
sequence-specific data to produce complete submissions.
.SH AUTHOR
The National Center for Biotechnology Information.
.SH SEE ALSO
.ad l
.BR sequin (1),
.BR tbl2asn (1).
