.TH TRNA2TBL 1 2005-11-04 NCBI "NCBI Tools User's Manual"
.SH NAME
trna2tbl \- convert tRNAscan-SE output to a Sequin feature table
.SH SYNOPSIS
.B trna2tbl
.SH DESCRIPTION
\fBtrna2tbl\fP is a filter that reads a text file produced by
tRNAscan-SE from its standard input and yields a corresponding
5-column feature table in the format understood by Sequin (and
\fBtbl2asn\fP) on its standard output.
.SH OPTIONS
None.
.SH AUTHOR
The National Center for Biotechnology Information.
.SH SEE ALSO
.BR sequin (1),
.BR tbl2asn (1),
.BR trna2sap (1).
